// <auto-generated />
using System;
using Credfeto.Dispatcher.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Credfeto.Dispatcher.Storage.Migrations
{
    [DbContext(typeof(DispatcherDbContext))]
    [Migration("20260519130139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Credfeto.Dispatcher.Storage.Entities.IssueEntity", b =>
                {
                    b.Property<string>("Repository")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsOnHold")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LinkedPrNumber")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("WhenClosed")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Repository", "Id");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Credfeto.Dispatcher.Storage.Entities.NotificationQueueEntity", b =>
                {
                    b.Property<string>("SubjectUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("DispatchAfter")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("SubjectUrl");

                    b.HasIndex("DispatchAfter");

                    b.ToTable("NotificationQueue");
                });

            modelBuilder.Entity("Credfeto.Dispatcher.Storage.Entities.PollingStateEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Key");

                    b.ToTable("PollingStates");
                });

            modelBuilder.Entity("Credfeto.Dispatcher.Storage.Entities.PullRequestEntity", b =>
                {
                    b.Property<string>("Repository")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<int>("FailedCheckCount")
                        .HasColumnType("int");

                    b.Property<string>("FailedCheckNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailedCheckSha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsOnHold")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ReviewDecision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("WhenClosed")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Repository", "Id");

                    b.ToTable("PullRequests");
                });

            modelBuilder.Entity("Credfeto.Dispatcher.Storage.Entities.RepoEntity", b =>
                {
                    b.Property<string>("Repository")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Repository");

                    b.ToTable("Repos");
                });
#pragma warning restore 612, 618
        }
    }
}
