CREATE TABLE [dbo].[PollingStates] (
  [Key] NVARCHAR(256) NOT NULL,
  [ETag] NVARCHAR(1024) NOT NULL,
  [DateCreated] DATETIMEOFFSET NOT NULL DEFAULT GETUTCDATE(),
  [DateUpdated] DATETIMEOFFSET NOT NULL DEFAULT GETUTCDATE(),
  [DateStateChanged] DATETIMEOFFSET NOT NULL DEFAULT GETUTCDATE(),
  CONSTRAINT [PK_PollingStates] PRIMARY KEY ([Key])
);
