@credfeto_dispatcher_HostAddress = http://localhost:8080

###

GET {{credfeto_dispatcher_HostAddress}}/ping
Accept: application/json

###

GET {{credfeto_dispatcher_HostAddress}}/priorities
Accept: application/json

###
